name: VuePress GitHub Actions

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.17.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i

      # run build script
      - name: Build VuePress site
        run: pnpm run docs:build
      
      # Deploy
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # deploy to docs branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: .vuepress/dist
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


